### DISCUSSION TITLE
Styling labels for form controls

### DISCUSSION THREAD

**Discussion by grahamford** [vmware/clarity#5846] [Q&A]
With version 4 of Clarity, we have customised the way form labels are displayed using these variables:
```
  --clr-forms-label-font-weight: normal;
  --clr-forms-checkbox-background-color: var(--blue);
  --clr-forms-focused-color: var(--orange);
  --clr-forms-label-color: var(--blue);
```

In version 5, I found this to set the focus colour but couldn't find anything for the other attributes.
```
--cds-alias-status-info: var(--orange);
```

Is it possible to set the other css attributes on a version 5 form control label?

**Comment by mathisscott** [comment]
[Here are different ways to do all those things](https://stackblitz.com/edit/core-v5-stackblitz-wy9bbg?file=index.html) in the Clarity Core (web component) forms. There's usually an easy way to get to these custom properties. It may take a little digging to get to the right ones. But once you find the ones you need, they are super easy to override.

**Reply by grahamford** [reply]
That's a good example Scott. However changing the font weight by updating this rule has no effect.
``` css
.my-custom-form label {
  font-weight: normal
}
```

It can't override the styling that comes from this: 
``` css
:host([action="primary"]) ::slotted([slot="label"]) {
    font-weight: bold !important;
}
```

Is there a way to target the formatting on the nested slotted content?
