### ISSUE TITLE
Support equal height/width cards similar to bootstrap 4.

### ISSUE THREAD

**Issue by FlashBanistan** [vmware/clarity#1469]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Cards can be wrapped in a "group" or "deck" similar to bootstrap 4 that will allow for equal width/height of the cards. [link](https://v4-alpha.getbootstrap.com/components/card/#card-decks) 

Right now I've hacked the CSS to make it work for me but I feel it would be beneficial to the community to have this as an option. [Plunkr](https://plnkr.co/edit/FBY0jgIZLq2JS6idpKnu?p=preview)  Simply remove the CSS to see it's current behavior.

**Comment by adityarb88** [comment]
@FlashBanistan: Thanks for filing this ticket. I will tag our UX team on the ticket so that they can provide their input on whether this feature is needed in Clarity because to implement this we would have to refactor card styles to use flexbox.

**Comment by reddolan** [comment]
@adityarb88 if we were to implement flexbox on the cards, would that give us greater flexibility in the future? 
I would say that it is more common to have aligned card heights than it is to have columns where the cards don't align.

**Comment by adityarb88** [comment]
Flexbox in general would give us greater flexibility but it also depends on the feature that we want to add to cards. Do you think this should be an option (like a class) which when enabled makes the card heights same in a grid or should this be the default behavior?

**Comment by reddolan** [comment]
Let's go with this being an optional class and keep our default as it stands now. This will keep us from having a breaking change too.

**Comment by yelhouti** [comment]
what about using css grid layout, wouldn't it help for this special case?

**Comment by mathisscott** [comment]
I also recommend CSS grid for this. It's doable with flex box but will be a pain.

**Comment by miohtama** [comment]
If someone looks for inspiration here is my quick example using CSS grid.

(Currently displays only two items in the screenshot)

![image](https://user-images.githubusercontent.com/49922/76805651-9ac21500-67df-11ea-9a9f-32aaf156c66b.png)

Angular template

```html
<div class="card-deck">
  <a href="#" class="card clickable" *ngFor="let entry of providerEntries">
    <div class="card-img">
      <img [src]="entry.logo" alt="{{ entry.name }}"/>
    </div>
    <div class="card-block">
      <div class="card-text">
        <h4 class="text-center">{{ entry.name }}</h4>

        <p class="text-center">{{ entry.description }}</p>
      </div>
    </div>
  </a>
</div>
```

SCSS stylesheet

```scss
// https://stackoverflow.com/a/48763724/315168
.card-deck {

  display: grid;

  // Space between items 
  grid-gap: 5px;
  
  // Decide the number of columns and size 
  grid-template-columns: 1fr 1fr 1fr 1fr;
  
  .card {
    width: 200px;

    .card-img  {
      padding: 10px;

      // Set size for a SVG image
      img {
        max-height: 96px;
        margin: 0 auto;
      }
    }
  }
}
```
