### ISSUE TITLE
card list items with badges

### ISSUE THREAD

**Issue by WuglyakBolgoink** [vmware/clarity#1506]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

![bildschirmfoto 2017-09-25 um 09 47 52 kopie](https://user-images.githubusercontent.com/2271337/30797604-e621a1fe-a1d6-11e7-84f6-c6f9e0646853.png)

### Actual behavior
 
![bildschirmfoto 2017-09-25 um 09 47 52](https://user-images.githubusercontent.com/2271337/30797608-ea9e7964-a1d6-11e7-8af2-299bc1ddc522.png)

is it possible to add `badge`-icon on the right side of list item? or maybe any other `span` block?

**Comment by youdz** [comment]
I'll let UX decide if this is a valid request. In the meantime, here is an easy way to do it in your app without waiting for the feature: https://plnkr.co/edit/4203nv?p=preview
All I did was give the list group with a badge the following styles:
```css
.list-item-with-badge {
  display:flex;
  justify-content: space-between;
  align-items: center;
}
```
