### ISSUE TITLE
Datagrid - long column headers overlap next column header when sorting

### ISSUE THREAD

**Issue by grreeenn** [vmware/clarity#1725]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Next column would move right when the sorted column header expands 

### Actual behavior
When sorting some column, its header expands to include the sorting icon, but the next column remains where it was. When sorting by column with long name, its header overlaps the next one

### Reproduction of behavior
Make a datagrid with enough columns to fill the width, give one of the column some ReallyLongName and try to sort by it
https://plnkr.co/edit/F4ODz2cLELOMB7xncPQp?p=preview - sort by any of VeryLongColumn names

### Environment details

* **Angular version:** 
5.0.1

* **Clarity version:**
0.10.13
* **OS and version:** 
Windows 10
* **Browser:** 
Chrome 62.0.3202.94
FF 56.0

**Comment by marcelocarmona** [comment]
### Overlapping also occur in the row
![grid](https://user-images.githubusercontent.com/4614400/33573986-5c5ef5d0-d916-11e7-80c0-825f1b1c11d5.gif)
https://plnkr.co/edit/vq243E?p=preview

**Comment by grreeenn** [comment]
Hi @marcelocarmona,  what you're talking about is defined as an expected behavior - see https://github.com/vmware/clarity/issues/618

**Comment by marcelocarmona** [comment]
Hi @grreeenn thanks, I had not seen that issue.

**Comment by Shijir** [comment]
@grreeenn @marcelocarmona This issue might have a simple workaround if you specify the style of handling word breaks in the datagrid columns and cells:

```css
.datagrid-column, .datagrid-cell {
  overflow-wrap: break-word;
  word-wrap: break-word;
  -ms-word-break: break-all;
  word-break: break-word;
  -ms-hyphens: auto;
  -moz-hyphens: auto;
  -webkit-hyphens: auto;
  hyphens: auto;
}
```

This is the result: https://plnkr.co/edit/nyo8KOcVMitktCjNwrJ0?p=preview
