### ISSUE TITLE
Responsive Wizard

### ISSUE THREAD

**Issue by furti** [vmware/clarity#2482]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[ x ] enhancement
```

### Expected behavior

The Wizard component should adapt to different screen sizes. Something like this:

![image](https://user-images.githubusercontent.com/2047555/43077389-aadd7c14-8e87-11e8-9b8d-6872c4b3bd7c.png)

There is room for improvement for sure. I needed an easy way to use the wizard on a responsive page. So i came up with the above solution as this was possible by tweaking the css a bit.

### Actual behavior

Currently the wizard stays the same no matter how small the screen is.
![image](https://user-images.githubusercontent.com/2047555/43077479-e5f34536-8e87-11e8-91be-44ff4db56edb.png)

### Reproduction of behavior

Go to https://vmware.github.io/clarity/documentation/v0.12/wizards with a Mobile Device or with Chrome and enable emulation in the DevTools.

### Environment details

* **Angular version:** 5.2.10

* **Clarity version:** 0.11

* **OS and version:** Windows 10

* **Browser:** [all]

**Comment by furti** [comment]
If someone is searching for a solution, here is the scss i used for this. Be aware that this version is not tested in a lot of different browsers right now.

```scss
/**************
 * Wizard
 */
@media screen and (max-width: 768px) {
    .clr-wizard {
        .modal-dialog {
            height: 100% !important;
            width: 100% !important;
        }

        .modal-content-wrapper {
            flex-direction: column;
        }

        .clr-wizard-title {
            margin-bottom: 0.5rem;
        }

        .modal-nav.clr-wizard-stepnav-wrapper,
        .modal-content {
            min-width: 100%;
        }

        .modal-nav.clr-wizard-stepnav-wrapper {
            height: auto;
            border-right: none;
            border-bottom: 1px solid $clr-wizard-step-nav-border-color;
        }

        .clr-wizard-stepnav-list {
            display: flex;
            flex-wrap: wrap;
        }

        .clr-wizard-stepnav-item {
            box-shadow: none;
            padding: 0;
            border-bottom: 0.16667rem solid $clr-wizard-stepnav-border-color;
            margin-right: 0.16667rem;
        }

        .clr-wizard-stepnav-item.complete {
            box-shadow: none;
            border-bottom: 0.16667rem solid $clr-wizard-stepnav-border-color--active;
            transition: border-bottom 0.2s ease-in;
        }

        .clr-wizard-stepnav-item.active .clr-wizard-stepnav-link {
            background-color: inherit;
        }

        .clr-wizard-stepnav-link {
            height: 1rem;
            padding: 0;
        }

        .clr-wizard-stepnav-link::before {
            display: none;
        }

        .clr-wizard-stepnav-item:not(:last-child) .clr-wizard-stepnav-link:after {
            content: '\203A';
            padding: 0 0.16667rem;
        }
    }
}
```

**Comment by GaryHyland** [comment]
Hmm - I was looking for the wizard page and it is NOT listed in the v0.12 left nav component menu. Have to find it in the component list page.

**Comment by furti** [comment]
Hmm... strange. For me it is listet in the left nav for v0.12.
![image](https://user-images.githubusercontent.com/2047555/43128335-0b998b88-8f32-11e8-85ed-5bac5b46c5ae.png)
![image](https://user-images.githubusercontent.com/2047555/43128344-142e6264-8f32-11e8-9c32-1134a73f2066.png)

**Comment by catwell** [comment]
I had the same issue and went with something a lot more radical:


```scss
@media screen and (max-width: 768px) {
  .clr-wizard {
    .modal-dialog {
      height: 100% !important;
      width: 100% !important;
    }

    .modal-content {
      min-width: 100%;
    }

    .modal-nav.clr-wizard-stepnav-wrapper {
      display: none;
    }
  }
}
```
