### ISSUE TITLE
Multiple App level Alerts have incorrect rendering on low resolution screen

### ISSUE THREAD

**Issue by ronymesquita** [vmware/clarity#2655]
## Summary
Multi-Alert component appears incorrectly on low resolution screens.

### Expected behavior
Correct render on low resolution screens.

### Examples
Open the Clarity's site on the browser and resize.

![clarity](https://user-images.githubusercontent.com/41541500/45545059-80c10400-b7ef-11e8-934b-c84a691fd24e.png)

## API

Is possible to use the styles below. The code is on the file app.component.scss. Repository: https://github.com/ronymesquita/project-with-clarity

```css
@media only screen and (max-width: 768px) {
    .alert-item .alert-icon-wrapper {
        align-self: center;
        margin-top: 0;
  }

  .alert-item .alert-text {
      margin: 0;
      max-width: 100%;
      width: auto;
      flex-basis: unset;
  }

  .alert-item .alert-actions {
      flex: unset;
  }
}
```
