### ISSUE TITLE
clr-textarea is not positioning the error icon correctly

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#2879]
## Describe the bug

I have a form layout where input controls (e.g. input, text area) must be stretched to the width of the form. However, when validation icons appear, the icon in the text area control is placed inside the text area container so the width of the text area is reduced.
![image](https://user-images.githubusercontent.com/1977391/48963845-be53c180-efd6-11e8-9b2f-8328e6e600ff.png)

## How to reproduce

```html
<form class="setup-form" [formGroup]="setupForm">
    <clr-input-container>
        <label for="name">Tell us the name of your company</label>
        <input type="text" clrInput formControlName="name" />
    </clr-input-container>
    <clr-input-container>
        <label for="phone">What's your company phone no.</label>
        <input
            type="tel"
            formControlName="phoneNumber"
            clrInput
            placeholder="ex. (+1) 555 1234"
        />
    </clr-input-container>
    <clr-textarea-container>
        <label for="address">Where is it located?</label>
        <textarea
            rows="4"
            clrTextarea
            formControlName="address"
            placeholder="Type your company address"
        ></textarea>
    </clr-textarea-container>
    <button
        class="btn btn-primary"
        (click)="setupCompany()"
        [clrLoading]="loading"
    >
        Let's Get Started
    </button>
</form>
```
```scss
.setup-form {
    width: 100%;

    ::ng-deep .clr-control-container,
    ::ng-deep .clr-input-wrapper {
        width: 100%;
    }

    input {
        width: 100%;
    }

    textarea {
        width: 100%;
    }

    button {
        margin-top: 1rem;
        width: 100%;
    }
}
```
## Expected behavior

clr-textarea should layout validation icons like other clr-input controls

## Versions

**App**

* Angular: [e.g. 6] 7
* Node: [e.g. 8.10.0] 8+
* Clarity: [e.g. 0.12.5] 1.0.0-beta.2

**Device:** Dell XPS 13

* Type: [e.g. MacBook] Ultrabook
* OS: [e.g. iOS] Windows 10
* Browser [e.g. chrome, safari] Chrome
* Version [e.g. 22] latest

## Additional notes

_Add any other notes about the problem here._
