### ISSUE TITLE
clarity grid required form mark miss issue

### ISSUE THREAD

**Issue by BennieMeng** [vmware/clarity#3080]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._
code here
```html
<div class="form-group clr-row">
	<div class="clr-col-lg-2 clr-col-md-12 clr-col-sm-12 clr-col-xs-12">
		<label for="pv_type" class="required">
			PV类型
		</label>
	</div>
</div>
```
there should be a red star after label, but there is not one.
## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

## Expected behavior

_A clear and concise description of what you expected to happen._

after check, i found the 1.0.4 version grid , class change to prefix with clr-, this doesn't match
``` css
form .form-group > label:first-child,form .form-group > span:first-child,form .form-group.row > [class*='col-'] > label,form .form-group.row > [class*='col-'] > span,.form .form-group > label:first-child,.form .form-group > span:first-child,.form .form-group.row > [class*='col-'] > label,.form .form-group.row > [class*='col-'] > span
```
reqire
```css
form .form-group > label:first-child.required:after, form .form-group > span:first-child.required:after, form .form-group.clr-row > [class*='clr-col-'] > label.required:after, form .form-group.clr-row > [class*='clr-col-'] > span.required:after, .form .form-group > label:first-child.required:after, .form .form-group > span:first-child.required:after, .form .form-group.clr-row > [class*='clr-col-'] > label.required:after, .form .form-group.clr-row > [class*='clr-col-'] > span.required:after {
     content: '*';
     font-size: 0.58479532rem;
     line-height: 0.5rem;
     color: #c92100;
     margin-left: 0.25rem;
}
```

## Versions

**App**

* Angular: [e.g. 7.2.2]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 1.0.4]

**Device:**

* Browser [e.g. chrome, safari]
## Additional notes

_Add any other notes about the problem here._
