### ISSUE TITLE
Datagrid component renders very slow/sluggish scrolling when there are third-party Angular components installed

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#3105]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._

Some mainstream components such as a scheduler or a calendar and charts are not available in Clarity so I incorporated third-party components like DevExtreme open-source and Wijmo trial version. All these third-party components worked perfectly fine. However, Clarity's datagrid becomes janky. Scrolling is also sluggish. Even the vertical nav component's scrolling behavior is not smooth. I tried to remove Wijmo components, and left DevExtreme, then tried removing DevExtreme and left Wijmo. Still, the datagrid renders very slow while the third-party components are working perfectly. Removing all third party components, the grid's rendering normally.

I'm not sure if this is related to #3082 

## How to reproduce
Just throw in some third party components specifically DevExtreme or Wijmo

## Expected behavior

Performance should not be affected by external components.

## Versions

**App**

* Angular: 7
* Node: 10+
* Clarity: 1.0.5

**Device:**

* Type: Dell XPS 13
* OS: Windows 10
* Browser Chrome
* Version 72.0+

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
This is a pretty challenging issue to triage from just a description. Can you setup a demo of this for us to review? This can easily be due to a large number of factors, from the external components, to your implementation, to our components.

**Comment by whizkidwwe1217** [comment]
@gnomeontherun Sorry for the late feedback. I spent hours of digging into my code just to find out what's causing the performance issue in the data grid. I just figured out that the one that's causing the very sluggish scrolling is the dynamic row hover feature that I've implemented. It's just weird that it only happens when external components are initialized. Anyway, I'll close this ticket for now and try to find alternative solutions. Thanks 🙂

```html
<clr-dg-cell
    *ngIf="canShowQuickActions('start')"
     style="display: inline-flex"
>
<a
  *ngIf="enableDelete && !readonly"
  [ngClass]="{
    'floating-cell-action': false,
    'always-visible-cell-action': true
  }"
 title="Delete"
  >
         <clr-icon style="color: #F76F6C" shape="trash"></clr-icon>
    </a>
</clr-dg-cell>
```
```css
.floating-row:hover .floating-cell-action {
	visibility: visible;
	opacity: 1;
}

.always-visible-cell-action {
	visibility: visible;
	padding: 0 0.25rem;
	opacity: 1;
}

.floating-cell-action {
	visibility: hidden;
	padding: 0 0.25rem;
	opacity: 0;
	transition: 100ms ease-in all;
}
```
![image](https://user-images.githubusercontent.com/1977391/52853936-ff7feb80-3157-11e9-914d-ed3582d247db.png)
