### ISSUE TITLE
clr-dg-action-overflow cause vertical scrollbar in datagrid

### ISSUE THREAD

**Issue by zwerg44** [vmware/clarity#3161]
## Describe the bug

When I click on the action button in the last row of the datagrid, vertical scrollbar apprears.

![default](https://user-images.githubusercontent.com/7299028/53735181-31eb5180-3e97-11e9-8ca1-22e35c420314.png)

## How to reproduce

It is reproducible in the documentation page.

Click on the action button in the last row of this example:
https://clarity.design/documentation/datagrid/single-action

## Expected behavior

No vertical scrolbar.

![default](https://user-images.githubusercontent.com/7299028/53735369-afaf5d00-3e97-11e9-813b-a0a9dbfadd86.png)

## Versions

**App**

* Angular: 7.2.0
* Node: 10.15.1
* Clarity: 1.1.0

**Device:**

* Type: desktop PC
* OS: Ubuntu 16.04
* Browser Firefox 65.0.1 / Chromium 71.0.3578.98
* Version 65.0.1 / 71.0.3578.98

## Additional notes

Currently I'm using this css to fix the issue:

```css
.datagrid {
  z-index: 1;
  position: relative;
  overflow: visible !important;
}

.datagrid-footer {
  z-index: 0;
  position: relative;
}
```
Not sure that it is ok, to use `overflow: visible` here.
