### ISSUE TITLE
SCSS helpers no longer use maps ... they use hard coded chains of if/else making it impossible to define custom buttons

### ISSUE THREAD

**Issue by Rush** [vmware/clarity#3444]
## Describe the bug

It should be possible to generate a custom button using Clarity helpers ... Instead, the previously flexible functions have been refactored to be chain of if/elses, preventing from having any flexibility.

Previously I was able to define a custom `$clr-global-button-properties-map` with my custom button type.

Changes have been done as part of https://github.com/vmware/clarity/issues/2946 https://github.com/vmware/clarity/pull/3207 @mathisscott 

Clarity 2.0.0:
```scss
@function getSassButtonColor($type: default, $property: null) {
  @if $property == null {
    @return null;
  }

  @if $type == default {
    @return lookupFromDefaultButtonColors($property);
  }

  @if $type == default-outline {
    @return lookupFromDefaultOutlineButtonColors($property);
  }

  @if $type == primary {
    @return lookupFromPrimaryButtonColors($property);
  }

  @if $type == success {
    @return lookupFromSuccessButtonColors($property);
  }

  @if $type == success-outline {
    @return lookupFromSuccessOutlineButtonColors($property);
  }

  @if $type == danger {
    @return lookupFromDangerButtonColors($property);
  }

  @if $type == danger-outline {
    @return lookupFromDangerOutlineButtonColors($property);
  }

  @if $type == link {
    @return lookupFromLinkButtonColors($property);
  }

  @if $type == inverse {
    @return lookupFromInverseButtonColors($property);
  }

  @if $type == icon {
    @return lookupFromIconButtonColors($property);
  }

  @return null;
}

@mixin populateButtonProperties($button-type: default) {
  border-color: getSassButtonColor($button-type, border-color);
  background-color: getSassButtonColor($button-type, bg-color);
  color: getSassButtonColor($button-type, color);

  //To override the visited state of anchor links styled as buttons
  &:visited {
    color: getSassButtonColor($button-type, color);
  }

  &:hover {
    background-color: getSassButtonColor($button-type, hover-bg-color);
    color: getSassButtonColor($button-type, hover-color);
  }

  &:active {
    @if $button-type == link {
      box-shadow: none;
    } @else {
      box-shadow: 0
        getActiveWidthBoxShadowTop($button-type)
        0
        0
        getSassButtonColor($button-type, box-shadow-color)
        inset;
    }
  }

  &.disabled,
  &:disabled {
    color: getSassButtonColor($button-type, disabled-color);
    cursor: not-allowed;
    opacity: 0.4;
    background-color: getSassButtonColor($button-type, disabled-bg-color);
    border-color: getSassButtonColor($button-type, disabled-border-color);
    box-shadow: none;
  }
}
```

Previously in Clarity 1.0.0, declaring a custom map would let you define custom buttons:
```scss
@mixin populateButtonProperties($button-type: default, $button-global-map: $clr-global-button-properties-map) {
  $button-property-map: map-get($button-global-map, $button-type);
  border-color: map-get($button-property-map, border-color);
  background-color: map-get($button-property-map, background-color);
  color: map-get($button-property-map, color);

  //To override the visited state of anchor links styled as buttons
  &:visited {
    color: map-get($button-property-map, color);
  }

  &:hover {
    background-color: map-get($button-property-map, hover-background-color);
    color: map-get($button-property-map, hover-color);
  }

  &:active {
    box-shadow: 0 map-get($button-property-map, active-box-shadow-width-top) 0 0
      map-get($button-property-map, active-box-shadow-color) inset;
  }

  &.disabled,
  &:disabled {
    color: map-get($button-property-map, disabled-color);
    cursor: not-allowed;
    background-color: map-get($button-property-map, disabled-background-color);
    border-color: map-get($button-property-map, disabled-border-color);
    opacity: 0.4;
  }
}
```

## How to reproduce

Try to declare your own button type:
```scss
.btn.btn-secondary,
  .btn-secondary .btn {
    @include populateButtonProperties(secondary);
  }

  .btn.btn-secondary-outline,
  .btn.btn-outline-secondary,
  .btn-secondary-outline .btn,
  .btn-outline-secondary .btn {
    @include populateButtonProperties(outline-secondary);
  }
```
Due to hard coded if/else chain in `populateButtonProperties`, it's not really possible to declare new button types anymore. 

## Expected behavior

SCSS functions and helpers should have flexibility to generate styles for new types buttons (and other components possibly)

## Versions
* Clarity: 2.0.0

## Additional notes

The issues with SCSS have originally been discussed over here https://github.com/vmware/clarity/issues/2442
