### ISSUE TITLE
Accordion styling issue: 

### ISSUE THREAD

**Issue by furti** [vmware/clarity#3685]
## Round corners on last panel

When the last panel of a accordion is expanded, the bottom corners of the panel are still rounded. And it seems that there are two borders at the bottom of the panel.

I consider this as a minor inconsistency as the stackview does not have rounded corners and duplicated borders for the last panel.

### Accordion
![image](https://user-images.githubusercontent.com/2047555/62767641-6e9a2500-ba95-11e9-8929-573af3482bb2.png)

### Stack View
![image](https://user-images.githubusercontent.com/2047555/62767663-7ce84100-ba95-11e9-9d34-b8875e49dfae.png)

## How to reproduce

Go to https://clarity.design/documentation/accordion and open the last panel of the example accordion to see the rounded corners.

Go to https://clarity.design/documentation/stack-view and open the last panel of the example stack view to see no rounded corners.

## Expected behavior

There should be no rounded corners and duplicated borders on the last panel of the accordion.

## Versions

**App**

Clarity Documentation for v2.

**Device:**

* Type: Notebook
* OS: Windows 10
* Browser chrome
* Version 67

**Comment by furti** [comment]
As a workaround I added this styles to my scss files.

```scss
.clr-accordion:not(.clr-stepper-forms) .clr-accordion-panel:last-child {
    .clr-accordion-panel-open {
        .clr-accordion-header {
            border-bottom-left-radius: 0;
            border-bottom-right-radius: 0;
            border-bottom: none;
        }
    }
}
```
