### ISSUE TITLE
Core: remove global style references

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#4061]
Clean up global style references and any style APIs that would cause breaking changes after 3.0
- [x] remove all component margins
- [x] remove global styles for 3.0 (typography/layout)
- [x] remove use of global css props internally with core components
- [x] remove global prefix convention on host scoped styles

## Margins
Ensure all core components have no specified `:host` margins. Margins on a host element make assumptions of the layout that is external to their responsibility. Using a design token system designers and developers should be able to layout components consistently and with specified intent and constraint. The design token values are still a wip but we want to remove margins before 3.0 to prevent future visual breaking changes.

Core will need to handle design tokens and variables slightly different than clr-ui/angular due to shadow dom and component composition but we should align the space values for the token to stay consistent.

Related issues/context:
https://github.com/vmware/clarity/issues/181
https://github.com/vmware/clarity/issues/4116
https://github.com/vmware/clarity/issues/3303

## Layout & Typography
Both the layout/grid utilities and typography also suffer from inconsistent layout margins (not typographic whitespace) and spacing. For 3.0 we will omit these from the core global styles until they can be addressed. Also defining non global explicit utils will allow possible migration strategies with scoped utils.

## Global CSS Properties
Core Components should not reference global CSS custom properties as this creates a secondary way to theme components and creates twice the API surface area. Our clr-ui dark theme follows a similar pattern and only changes the local component scoped variables leaving global values unchanged. For core components to share values such as spacing and color they internally should use private sass variables and not global CSS Custom Properties.

## Global Prefixing
Public API surface for component styling should not use the global prefixing convention. This is necessary for micro frontends where a component may need to be aliased due to app embedding. This prevents version collisions and dependencies form having to share the same global values.

```css
cwc-badge {
  --color: red;
  --background: blue;
}
```

Teams can prefix their own core components to share and embed with other products without the risk of a host app breaking their product specific styles.

```html
<style>
  cwc-badge {
   --color: green;
  }
</style>
<cwc-badge></cwc-badge> <!-- only host application badges are changed -->

<product-cwc-badge></product-cwc-badge> <!-- embedded product styles are preserved -->
```

In very rare cases a naming collision can occur with a local host var and global theming var breaking on the component ([see example](https://codepen.io/coryrylan/pen/vYEMxgo)).

```scss
// global scope
:root {
  --primary-color: blue;
}

// component scope (:host)
button {
  // naming colision, due to global and local names
  // var cant resolve to global or local but refers to
  // its own redeclartion defaulting to initial.
  --primary-color: var(--primary-color);
  background: var(--primary-color);
}
```
