### ISSUE TITLE
core: align component theme APIs

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#4062]
To support flexible theming for core components we need to check that we follow the following architecture with CSS Custom Props. This also reduces the number of stateful variables we have to create. If a new `status` is added we do not have to introduce two new variables to be able to configure the new status type.

```scss
:host {
  --clr-button-background: #{$clr-global-blue-100};
  --clr-button-color: #{$clr-global-blue-300};
  background: var(--clr-button-background};
  color: var(--clr-button-color);
}

:host[status="danger"] {
  --clr-button-background: #{$clr-global-red-100};
  --clr-button-color: #{$clr-global-red-300};
}
```

This architecture allows custom classes/states to be defined by the consuming application. This encourages apps stay consistent and use custom states instead of modifying the entire look and feel of Clarity globally.

```scss
// Public API
cwc-button {
  --clr-button-background: green;
  --clr-button-color: darkgreen;
}

cwc-button.product-button {
  --clr-button-background: purple;
  --clr-button-color: darkpurple;
}
```

```html
<cwc-buitton class="product-button">my purple product specific brand button</cwc-button>
```

- [x] alerts
- [x] icon
- [x] badge
- [x] tag
- [x] button
- [x] document pattern in contribution guidelines
