### ISSUE TITLE
Clarity V2 accordion title overflows when the div width is smaller than 7.2 rem.

### ISSUE THREAD

**Issue by jinggongvmware** [vmware/clarity#4065]
The accordion title overflows when the width of the div shrank below certain width. It seems like there is a min-width of 7.2rem of the title even though the outer box could be smaller than that.
![Screen Shot 2019-12-02 at 4 23 15 PM](https://user-images.githubusercontent.com/42680949/70005926-198c8e00-1520-11ea-9b44-e81e70c8e097.png)

https://stackblitz.com/edit/clarity-light-theme-v2-xcymvs?file=src%2Fapp%2Fapp.component.ts

**Comment by coryrylan** [comment]
After inspecting the demo this looks like a bug. The title of the accordion was to have a minimum width when used within a stepper. This was to align the description of the stepper in the original design spec. The fix is to make sure that the min width is only applied to the title when in the stepper. Here is the source bug.

```scss
@media (min-width: 576px) {
  .clr-accordion-title { // should only apply when in stepper
    min-width: 7.2rem;
  }
}
```
