### ISSUE TITLE
Scrollbar for Dropdown menus

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#4182]
## Summary

Dropdowns with many items currently either cause a scrollbar to appear on some parent container or are clipped (depending on positioning). An option to opt-in to a scrollbar inside the dropdown option container itself would be nice. Maybe with a setting for the number of visible options before the scrollbar appears.

## Use case

In my case a text editor with a lot of font families to choose from suffers from this problem. A scrollbar would help here.

Maybe you plan to solve this with the Combobox? But it could also be a nice feature for the normal Dropdown.

## Workarounds

Add some CSS:

```css
.dropdown-menu {
  max-height: calc(10 * 1.5rem);
  overflow-y: scroll;

  .dropdown-item {
    min-height: 1.5rem;
  }
}
```
