### ISSUE TITLE
core: icon styles API proposal

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#4193]
Currently the clr-icon uses a classname based API to apply certain styles while using attrs for others. To follow best practices and consistency we should deprecate the class based API and provide a property/attribute based API for users to migrate to.

https://developers.google.com/web/fundamentals/web-components/best-practices#do-not-self-apply-classes.

```html
<clr-icon class="is-solid"></clr-icon>
<cwc-icon solid></cwc-icon>

<clr-icon class="is-inverse"></clr-icon>
<cwc-icon inverse></cwc-icon>

<clr-icon class="has-alert"></clr-icon>
<cwc-icon alert></cwc-icon>

<clr-icon class="has-badge"></clr-icon>
<cwc-icon badge></cwc-icon>

<clr-icon class="has-badge--success"></clr-icon>
<cwc-icon badge="success"></cwc-icon>
```

```typescript
// properties with defaults (auto reflects to attr)
@property({ type: Boolean }) solid = false;
@property({ type: Boolean }) inverse = false;
@property({ type: Boolean }) alert = false;
@property({ type: String }) badge = 'danger'; // [info | warning | danger | success]
```

## JavaScript
```typescript
// deprecated example toggle
const icon = document.querySelector('clr-icon');
if (icon.classList.contains('is-solid')) {
  icon.classList.remove('is-solid');
} else {
  icon.classList.add('is-solid');
}

// proposed example toggle
const icon = document.querySelector('cwc-icon');
icon.solid = !icon.solid;
```

## Angular
```html
<cwc-icon [solid]="isSolidProperty"></cwc-icon>
```

## Vue
```html
<cwc-icon :solid="isSolidProperty"></cwc-icon>
```

## Example Update

```typescript
@property({ type: Boolean }) alert = false;
```

```scss
:host([class*='has-alert']) .can-alert,
:host([alert]) .can-alert { // new line here that uses the new reflected attribute
  .clr-i-outline--alerted {
    display: block;
  }

  .clr-i-outline:not(.clr-i-outline--alerted) {
    display: none;
  }
}
```
