### ISSUE TITLE
core: align exposed public style APIs and update contribution guidelines

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#4263]
## Proposal
Ensure the exposed public styles globally and locally at the component level are consistent and expose the appropriate styles. We should add this to the contribution guidelines.

## CSS Props Component
- only expose non layout styles (background, color, box-shadows)
- prefer exposing shorthand values unless the shorthand alters sizes like border
   `border-color: var(--border-color)` not `border: var(--border)`
- colors should use global vars and fall back to hard coded sass vars so components render independently without requiring global styles.
  ```scss
  :host {
    --color: var(--clr-color-neutral-0, #{$clr-color-neutral-0});
    --background: var(--clr-color-action-600, #{$clr-color-action-600});
    --border-color: var(--clr-color-action-600, #{$clr-color-action-600});
    --box-shadow: 1 1 1 var(--$clr-color-neutral-600, #{$clr-color-neutral-600});  
  }
  ```
- Exposed properties should match the native CSS property and nested elements prefixed to prevent var name collisions.
  ```scss
  :host {
    // --[optional template element]-[css property]-[optional element state]: value;
    --icon-color-hover: var(...);
    --icon-color: var(...);
    --color: var(...);
    color: var(--color);

    &:hover {
      --color: var(--color-hover); 
    }

    cwc-icon {
      --color: var(--icon-color);
    }
  }
  ```
