### ISSUE TITLE
Alert text not vertically centered in the banner

### ISSUE THREAD

**Issue by YihongS** [vmware/clarity#4460]
## Describe the bug

The text within a standard alert banner is not vertically centered, which makes it looks weird when there's only one line in the alert.
![image (3)](https://user-images.githubusercontent.com/32996499/78930952-d4daab80-7a59-11ea-8cc8-fe04d1ef7863.png)
The small alert banner doesn't have this problem.

## How to reproduce

Just go to Clarity documentation page: https://v2.clarity.design/alerts

## Expected behavior

The text should be vertically-centered in the alert banner.

## Versions

**Device:**

* Type: MacBook Pro
* OS: macOS
* Browser: Safari
* Version: 13.1

**Comment by bdryanovski** [comment]
It seems that this issue is contained only on the website.

```css
.alert-items {
  flex: 1 1 auto;
  flex-flow: column nowrap;
  padding: .4rem .55rem;
  display: flex;
}
```
The padding must be `padding: .5rem .55rem;`
