### ISSUE TITLE
Core: Themes Research

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#4705]
## Research Support theming APIs in Core
- [ ] Research various systems and how css prop inheritance hierarchy is managed
- [ ] What can ie11 handle?
- [ ] Diagram out each theme level and how css props would behave
  - System: global tokens (size, color, typography)
  - Component: values customizable to the component
  - Scenario: values customizable to the instance of a component
  - High Level Aliases (maybe): primary, secondary, danger, success, warn
- [ ] Research how to manage multi state props. Ex button has 5 props but has n+ variations/color/sizes. 
- [ ] Should components even have tokens specific to them or simply use the system wide token values like color, space, and typography?
- [ ] Research into ways to ensure public API is easily surfaced and documented

### Known Tasks
- [ ] migrate tokens from yml to json5 in format for easier tooling and multi file support with Theo

Theo and component token files will allow us to generate the cssprops metadata for docs as well as store the theme values in a single isolate file for each component.

## Example Strategies:
- https://ionicframework.com/docs/theming/basics
  CSS var/parts looks to be the most mature web component based system out there
- https://www.fast.design/docs/design/introduction
  JavaScript based system
- https://www.carbondesignsystem.com/guidelines/themes/overview
  Sass based system (might be migrating to CSS var/parts
- https://www.sarasoueidan.com/blog/style-settings-with-css-variables/ 
   CSS Var only based system

## Some additional notes from my wip blog post

- wip demo https://stackblitz.com/edit/js-tts5hu?file=index.js

### System Tokens
- Color
- Typography
- Space

```scss
:root {
  // color
  --ds-token-red-100: hsl(5, 100%, 50%);
  --ds-token-blue-100: hsl(5, 100%, 50%);
  --ds-token-green-100: hsl(5, 100%, 50%);

  // space
  --ds-token-space-size-1: 2px;
  --ds-token-space-size-2: 4px;  
  --ds-token-space-size-3: 6px;
}
```

### Component

Most components have some form of built in style states (theme attrs state="danger")

```html
<ds-alert status="danger">
  Click Me
</ds-alert>
```

Custom needs to handle additional states like hover, focus, active. Also complex components which internal elements need custom styles not just the :host element. Quickly css props can become hard to manage.

```scss
ds-alert {
  --background: grey;
  --color: white;
 
  // complex states and nested elements
  --close-button-color: black;
  --close-button-color-hover: grey;

  // multi state 1:1 mapping to token? Or map to private token that is not exposed as custom prop? 
  --close-button-color-danger: red;
  --close-button-color-hover-danger: pink;
  --close-button-color-success: green;
  --close-button-color-hover-success: lime;
  ... 
}
```

Ex button has 5 props but has n+ variations/color/sizes/state. This can quickly balloon into a lot of props if each state is represented as a token/prop. This is where CSS Parts can be helpful see (https://ionicframework.com/docs/theming/css-shadow-parts)

Custom (css props/part)

```css
ds-alert::part(status-icon) {
  background: var(--cds-token-color-neutral-1000);
  color: var(--cds-token-color-neutral-0);
  padding: var(--cds-layout-space-3);
}
```

CSS Parts allow us to expose only certain elements for theming. This preserves the ability to change DOM structure without breaking the API. Instead of defining many css props for each element and each elements state we can expose a part reference to just that element. Example and alert may only have a few parts exposed such as `close-button`, `status-icon`, `container`.

## Component Level Tokens

CSS Parts can simplify the public CSS API for themes but how should these props be represented in the tokens file? Should they exist or simply reference the global system level tokens? Defining the values in a generic data format like using json/yml with a token system like theo allows them to be used outside of CSS.

However it could be difficult to maintain depending on the strategy in how we organize them and how far do we go with representing these values? Should we represent only the values that are customizable for themes? Should additional values like height, padding, width be defined? This is a open question as how do we determine what is a token and what is not? We don't want to rebuild CSS in a JSON file.

A simple approach is to define a single toke for each value with the token name defining all states within the name.

```yml
{
  - name: 'cds-alert-close-button-color',
     value: 'hsl(...)'
  - name: 'cds-alert-close-button-color-info',
     value: 'hsl(...)'
  - name: 'cds-alert-close-button-color-warning',
     value: 'hsl(...)'
  - name: 'cds-alert-close-button-color-danger',
     value: 'hsl(...)'
  - name: 'cds-alert-close-button-color-success',
     value: 'hsl(...)'
  - name: 'cds-alert-close-button-color-info',
     value: 'hsl(...)'

  - name: 'cds-alert-close-button-color-hover',
     value: 'hsl(...)'
  - name: 'cds-alert-close-button-color-info-hover',
     value: 'hsl(...)'
  - name: 'cds-alert-close-button-color-warning-hover',
     value: 'hsl(...)'
  - name: 'cds-alert-close-button-color-danger-hover',
     value: 'hsl(...)'
  - name: 'cds-alert-close-button-color-success-hover',
     value: 'hsl(...)'
  - name: 'cds-alert-close-button-color-info-hover',
     value: 'hsl(...)'
}
```

However this doesn't take into consideration that the status icon or close button in alert also has several display states `info`, `success`, `warning`, `danger`, `unknown`. With 5 visual states + any interaction states (hover, active, focus). This only represents the default theme. Additional themes like dark theme and a11y themes could push this even higher.

A possible options is better structure with describing each component. Break it down into the following

- parts (things that can be selected and styled)
- states (user states such as focus, hover)
- themes (allow override of the above based on particular theme)

By breaking into theme groups this could allow themes to be easily combined. Example an app could use the dark theme + a large touch target theme.

```json5
// default.theme.json
// each part exposed requires a default theme
{
  "cds-alert": {
    "parts": {
      "close-button": {
        "props": {
          "color": "hsl(...)",
          "background": "hsl(...)",
          "width": "...",
          "height": "..."
        },
        "states": {
          "hover": {
            "background": "hsl(...)"
          },
          "active": {
            "background": "hsl(...)"
          }
        }
      },
     "status-icon": {},
     "container": {}
    }
  }
}
```

```json5
// dark.theme.json
// themes instead of redefining all props can choose to only redefine properties they actually change.
// example: dark theme only changes color
{
  "cds-alert": {
    "parts": {
      "close-button": {
        "props": {
          "color": "hsl(...)",
          "background": "hsl(...)"
        },
        "states": {
          "hover": {
            "background": "hsl(...)"
          },
          "active": {
            "background": "hsl(...)"
          }
        }
      }
    }
  }
}
```

```json5
// a11y-large.theme.json
// a large touch target theme would not change color but only sizes
{
  "cds-alert": {
    "parts": {
      "close-button": {
        "props": {
          "width": "...",
          "height": "..."
        }
      }
    }
  }
}
```

A static structure will allow tokens to be generated that match the target platform, ex: CSS props, XML, JSON, JS...

## Refer to other tokens 

// todo: write out how Theo could reference existing tokens and what kind of code that could generate
