### ISSUE TITLE
Hovering over header nav <a> links has no effect

### ISSUE THREAD

**Issue by benash** [vmware/clarity#5745]
## Describe the bug

Hovering over a `header .header-actions a.nav-link` has no effect.

## How to reproduce

Create such an element, and hover over it.

## Expected behavior

Opacity should increase to 1, like it does when the link is a `<button>` instead of an `<a>`.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Device:**

- Type: MacBook
- OS: MacOS
- Browser: Chrome
- Version: M89

## Additional notes

The relevant CSS seems to be this, and the issue seems to stem from the `:enabled` component of the selector. Browsers don't seem to respect that pseudo-selector for `<a>`, only buttons, inputs, etc.:

```css
header .settings .nav-link:enabled:hover,
header .header-nav .nav-link:enabled:hover,
header .header-actions .nav-link:enabled:hover,
.header .settings .nav-link:enabled:hover,
.header .header-nav .nav-link:enabled:hover,
.header .header-actions .nav-link:enabled:hover {
  /* clr-header-nav-hover-opacity */
  opacity: 1;
  opacity: var(--clr-header-nav-hover-opacity, 1);
}
```
