### ISSUE TITLE
[ICONS] Inherit transform property

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#577]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Since the `<svg>` element inside a clarity icon is "kind of" private and is not part of my own template, I would like to be able to style 
```css
clr-icon[shape=caret] {
    transition: transform 0.2s ease-in-out;
}
```
and have the icon properly animate when I change its direction, for instance.
The fastest way to do this is simply to have the Clarity Icons CSS specify `transition: inherit` on its SVG element.

### Actual behavior

Right now, to achieve this, I have to write
```css
clr-icon[shape=caret] svg {
    transition: transform 0.2s ease-in-out;
}
```
It certainly isn't the worst, but it feels like I'm stepping into internal details by styling the SVG element myself. Same as what we did for `color` before.

### Reproduction of behavior

Currently working solution: https://plnkr.co/edit/1qAtWr?p=preview
