### ISSUE TITLE
Clarity icons flip option for horizontal or vertical flip

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#638]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
For some of the icons like the bolt/library/tags/etc... it would be better if clarity provided a way to flip the icon horizontally. Something similar in lines to font-awesome's 
fa-flip-horizontal, and 
fa-flip-vertical
example here: [http://fontawesome.io/examples/](url)

### Actual behavior
None

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Shijir** [comment]
Hi, @envyN! Thanks for suggesting this feature. As I am guessing this feature won't take much effort and time to implement, I think we could ship the feature in the near future.

In the meantime, if you need to flip `clr-icon`,  you could assign a class to flip `clr-icon` like this:

```css
clr-icon.flip-horizontally /deep/ svg{
    transform: scale(-1) rotateX(180deg);
}
clr-icon.flip-vertically /deep/ svg{
    transform: scale(-1) rotateX(180deg);
}
```
```html
<clr-icon shape="bolt" class="flip-horizontally"></clr-icon>
```
