### ISSUE TITLE
cds-icon in button misaligned when placed in clr-dropdown

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#6448]
## Describe the bug

The icons are not centered vertically.

![Screenshot 2021-11-02 at 15 37 07](https://user-images.githubusercontent.com/3655915/139868509-337150fc-d236-4466-b302-3b6f0b8fed5c.png)

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-clr12-cds5-of9ull

## Expected behavior

Centered icons

## Versions

**Clarity project:**

- [x] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

- [X] v5.6.0

**Framework:**

- [X] Angular

**Framework version:**
_ie: Angular 12.0.2

**Comment by dorthrithil** [comment]
The `.dropdown-toggle` style overrides margins, you can hotfix this bug using these styles:

```scss
.dropdown .dropdown-toggle.btn cds-icon{
  margin-top: -.14rem;

  &[shape=angle]{
    margin-top: -.1rem;
  }

}
```
