### ISSUE TITLE
[DataGrid] Long text overflows cell width

### ISSUE THREAD

**Issue by TechRazor** [vmware/clarity#815]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

DataGrid cells should have overflow hidden so that long continuous text such as website url's or email addresses do not overflow the column width.

### Actual behavior

Currently long continuous text overflows the cell width into text of the next cell.

### Reproduction of behavior

Screenshot of datagrid column title and datagrid cell overflow:
![image](https://cloud.githubusercontent.com/assets/1624021/25560119/bf9eb164-2d07-11e7-8102-77784f091fb6.png)

If I add 'overflow' and 'text-overflow' properties to '.datagrid-cell' in _datagrid.clarity.scss then I can get the cell to look proper, but making similar change to '.datagrid-column' or '.datagrid-column-title' make the column resize handle disappear during times when it overflows.

```css
    .datagrid-cell {
        flex: 1 1 auto;
        overflow: hidden;
        text-overflow: ellipsis;
        &.datagrid-fixed-width {
            flex: 0 0 auto;
        }
    }
```

![image](https://cloud.githubusercontent.com/assets/1624021/25560127/3c257006-2d08-11e7-99fe-691d1952add8.png)

### Environment details

* **Angular version:** 4.1.0

* **Clarity version:** 0.9.2

* **OS and version:** MacOS 10.12

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
